<script
   src="https://cdn.cookie3.co/scripts/analytics/0.11.4/cookie3.analytics.min.js"
   integrity="sha384-lzDmDdr/zEhMdlE+N04MgISCyL3RIWNCb9LjsrQeEFi8Gy5CKXIRI+u58ZV+ybYz"
   crossOrigin="anonymous"
   async="true"
   strategy="lazyOnload"
   data-site-id="1392"
   data-chain-tracking-enabled="true"
></script>
